rsync -av ~/.zshrc ~/Projects/dotfiles
rsync -av ~/.Xresources ~/Projects/dotfiles
rsync -av ~/.vimrc ~/Projects/dotfiles
rsync -av ~/.tmux.conf ~/Projects/dotfiles
rsync -av ~/.signature ~/Projects/dotfiles
rsync -av ~/.muttrc ~/Projects/dotfiles
rsync -av ~/.gitconfig ~/Projects/dotfiles
rsync -av ~/.bashrc ~/Projects/dotfiles
rsync -av ~/.config/kitty/kitty.conf ~/Projects/dotfiles
